### ISSUE TITLE
Remove generated by Hakyll Tag

### ISSUE THREAD

**Issue by harleyyyyymayes** [shymega/ttj-main-site#1]
Something that bothers me about the old site is that there is a tag at the bottom saying "Proudly Powered by WordPress" I believe it is not needed, please remove it from the footer of the site

**Comment by harleyyyyymayes** [comment]
Sorry, I should clarify, please remove the "Generated by Hakyll" tag from the footer of the new site

**Comment by shymega** [comment]
Hello,

Harley Mayes <notifications@github.com> writes:

> Sorry, I should clarify, please remove the "Generated by Hakyll" tag
> from the footer of the new site

I'm fine with doing that, as long as we make a page outlining the
backend of the TTJ site.

As a matter of principle, I think it's good to show how a site is
hosted, and to provide source code for others' benefit.

-- 
Best regards,
Dom Rodriguez
